monitor=,preferred,auto,1

source = ~/.config/hypr/theme.conf
source = ~/.config/hypr/saga-binds.conf

exec-once = waybar
exec-once = swaync
exec-once = swww-daemon
exec-once = eww daemon
exec-once = saga eww-stream
exec-once = saga ui-listen

input {
  kb_layout = us
  follow_mouse = 1
  touchpad {
    natural_scroll = true
  }
}

general {
  gaps_in = 6
  gaps_out = 12
  layout = dwindle
}

misc {
  disable_hyprland_logo = true
}
