#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="${1:-}"
if [[ -z "$REPO_ROOT" ]]; then
  REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fi

SHORTCUTS_FILE="$REPO_ROOT/config/shortcuts.json"
OUT_DIR="$HOME/.config/hypr"
OUT_FILE="$OUT_DIR/saga-binds.conf"
HYPR_CONF="$OUT_DIR/hyprland.conf"

if [[ ! -f "$SHORTCUTS_FILE" ]]; then
  echo "error: shortcuts config not found: $SHORTCUTS_FILE" >&2
  exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "error: jq is required for saga generate-binds" >&2
  exit 1
fi

mkdir -p "$OUT_DIR"

normalize_token() {
  local t
  t="$(echo "$1" | tr '[:lower:]' '[:upper:]' | xargs)"
  case "$t" in
    ENTER) echo "RETURN" ;;
    ESC) echo "ESCAPE" ;;
    *) echo "$t" ;;
  esac
}

to_hypr_bind_parts() {
  local shortcut="$1"
  local token key modifiers len i
  local parts=()

  IFS='+' read -ra raw_parts <<< "$shortcut"
  for token in "${raw_parts[@]}"; do
    parts+=("$(normalize_token "$token")")
  done

  if [[ "${#parts[@]}" -lt 2 ]]; then
    echo "error: invalid shortcut '$shortcut'. Use MOD+KEY format." >&2
    return 1
  fi

  len="${#parts[@]}"
  key="${parts[$((len - 1))]}"
  modifiers=""
  for ((i=0; i<len-1; i++)); do
    if [[ -z "$modifiers" ]]; then
      modifiers="${parts[$i]}"
    else
      modifiers="$modifiers ${parts[$i]}"
    fi
  done

  printf '%s|%s\n' "$modifiers" "$key"
}

bind_line() {
  local shortcut="$1"
  local command="$2"
  local parsed modifiers key

  parsed="$(to_hypr_bind_parts "$shortcut")"
  modifiers="${parsed%%|*}"
  key="${parsed##*|}"

  printf 'bind = %s, %s, exec, %s\n' "$modifiers" "$key" "$command"
}

launcher="$(jq -r '.launcher' "$SHORTCUTS_FILE")"
terminal="$(jq -r '.terminal' "$SHORTCUTS_FILE")"
control_center="$(jq -r '.control_center' "$SHORTCUTS_FILE")"
notifications="$(jq -r '.notifications' "$SHORTCUTS_FILE")"
wifi="$(jq -r '.wifi' "$SHORTCUTS_FILE")"
bluetooth="$(jq -r '.bluetooth' "$SHORTCUTS_FILE")"
audio="$(jq -r '.audio' "$SHORTCUTS_FILE")"
brightness="$(jq -r '.brightness' "$SHORTCUTS_FILE")"
system_stats="$(jq -r '.system_stats' "$SHORTCUTS_FILE")"
power="$(jq -r '.power' "$SHORTCUTS_FILE")"
file_search="$(jq -r '.file_search' "$SHORTCUTS_FILE")"

{
  echo "# Generated by saga generate-binds"
  echo
  bind_line "$launcher" "saga launcher app"
  bind_line "$terminal" "kitty"
  echo
  bind_line "$control_center" "saga panel toggle control_center"
  bind_line "$notifications" "swaync-client -t"
  bind_line "$wifi" "saga panel toggle wifi_menu"
  bind_line "$bluetooth" "saga panel toggle bluetooth_menu"
  bind_line "$audio" "saga panel toggle audio_menu"
  bind_line "$brightness" "saga panel toggle brightness_menu"
  bind_line "$system_stats" "saga panel toggle system_stats"
  bind_line "$power" "saga panel toggle power_menu"
  bind_line "$file_search" "saga launcher files"
} > "$OUT_FILE"

if [[ -f "$HYPR_CONF" ]]; then
  has_source=1
  if command -v rg >/dev/null 2>&1; then
    if rg -q '^\s*source\s*=\s*~/.config/hypr/saga-binds\.conf\s*$' "$HYPR_CONF"; then
      has_source=0
    fi
  else
    if grep -Eq '^[[:space:]]*source[[:space:]]*=[[:space:]]*~/.config/hypr/saga-binds\.conf[[:space:]]*$' "$HYPR_CONF"; then
      has_source=0
    fi
  fi

  if [[ "$has_source" -ne 0 ]]; then
    printf '\nsource = ~/.config/hypr/saga-binds.conf\n' >> "$HYPR_CONF"
    echo "updated: $HYPR_CONF (added saga binds source)"
  fi
fi

echo "generated: $OUT_FILE"
