#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="${1:-}"
THEME_NAME="${2:-saga-default}"

if [[ -z "$REPO_ROOT" ]]; then
  REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fi

THEME_DIR="$REPO_ROOT/themes/$THEME_NAME"
if [[ ! -f "$THEME_DIR/theme.json" ]]; then
  THEME_DIR="$REPO_ROOT/themes/saga-$THEME_NAME"
fi
THEME_JSON="$THEME_DIR/theme.json"

if [[ ! -f "$THEME_JSON" ]]; then
  echo "error: theme not found: $THEME_JSON" >&2
  exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "error: jq is required for saga theme apply" >&2
  exit 1
fi

primary="$(jq -r '.colors.primary' "$THEME_JSON")"
secondary="$(jq -r '.colors.secondary' "$THEME_JSON")"
accent="$(jq -r '.colors.accent' "$THEME_JSON")"
background="$(jq -r '.colors.background' "$THEME_JSON")"
glass="$(jq -r '.colors.glass' "$THEME_JSON")"
text="$(jq -r '.colors.text' "$THEME_JSON")"
text_muted="$(jq -r '.colors["text-muted"]' "$THEME_JSON")"
danger="$(jq -r '.colors.danger // "#ff4d6d"' "$THEME_JSON")"
success="$(jq -r '.colors.success // "#00f5a0"' "$THEME_JSON")"
font_ui="$(jq -r '.fonts.ui' "$THEME_JSON")"
font_size="$(jq -r '.fonts.size' "$THEME_JSON")"
space_xs="$(jq -r '.spacing.xs // 6' "$THEME_JSON")"
space_sm="$(jq -r '.spacing.sm // 10' "$THEME_JSON")"
space_md="$(jq -r '.spacing.md // 14' "$THEME_JSON")"
space_lg="$(jq -r '.spacing.lg // 20' "$THEME_JSON")"
radius="$(jq -r '.ui.radius' "$THEME_JSON")"
border_size="$(jq -r '.ui.border_size' "$THEME_JSON")"
blur="$(jq -r '.ui.blur' "$THEME_JSON")"
anim_windows="$(jq -r '.animations.windows' "$THEME_JSON")"
anim_workspace="$(jq -r '.animations.workspace' "$THEME_JSON")"
hrafn_agenda_time="$(jq -r '.hrafn.colors.agenda_time // .colors.secondary' "$THEME_JSON")"
hrafn_agenda_title="$(jq -r '.hrafn.colors.agenda_title // .colors.text' "$THEME_JSON")"
hrafn_task="$(jq -r '.hrafn.colors.task // .colors.success' "$THEME_JSON")"
hrafn_empty="$(jq -r '.hrafn.colors.empty // .colors["text-muted"]' "$THEME_JSON")"
hrafn_meeting_soon="$(jq -r '.hrafn.colors.meeting_starting_soon // .colors.primary' "$THEME_JSON")"
hrafn_meeting_live="$(jq -r '.hrafn.colors.meeting_live // .colors.success' "$THEME_JSON")"
hrafn_tasks_due="$(jq -r '.hrafn.colors.tasks_due_today // .colors.danger' "$THEME_JSON")"
hrafn_focus="$(jq -r '.hrafn.colors.focus_window_available // .colors.accent' "$THEME_JSON")"
hrafn_sync_status="$(jq -r '.hrafn.colors.sync_status // .colors.secondary' "$THEME_JSON")"
hrafn_error="$(jq -r '.hrafn.colors.error // .colors.danger' "$THEME_JSON")"
hrafn_warning="$(jq -r '.hrafn.colors.warning // .colors.accent' "$THEME_JSON")"
hrafn_font_ui="$(jq -r '.hrafn.fonts.ui // .fonts.ui' "$THEME_JSON")"
hrafn_font_display="$(jq -r '.hrafn.fonts.display // .fonts.ui' "$THEME_JSON")"
hrafn_font_size="$(jq -r '.hrafn.fonts.size // .fonts.size' "$THEME_JSON")"

cat > "$THEME_DIR/variables.css" <<CSS
:root {
  --saga-primary: $primary;
  --saga-secondary: $secondary;
  --saga-accent: $accent;
  --saga-bg: $background;
  --saga-glass: $glass;
  --saga-text: $text;
  --saga-text-muted: $text_muted;
  --saga-danger: $danger;
  --saga-success: $success;

  --saga-font-ui: "$font_ui";
  --saga-font-size: ${font_size}px;

  --saga-space-xs: ${space_xs}px;
  --saga-space-sm: ${space_sm}px;
  --saga-space-md: ${space_md}px;
  --saga-space-lg: ${space_lg}px;

  --saga-radius: ${radius}px;
  --saga-border-size: ${border_size}px;
  --saga-blur: ${blur}px;

  --saga-anim-windows: $anim_windows;
  --saga-anim-workspace: $anim_workspace;
}
CSS

cat > "$THEME_DIR/variables.scss" <<SCSS
\$saga-primary: $primary;
\$saga-secondary: $secondary;
\$saga-accent: $accent;
\$saga-bg: $background;
\$saga-glass: $glass;
\$saga-text: $text;
\$saga-text-muted: $text_muted;
\$saga-danger: $danger;
\$saga-success: $success;

\$saga-font-ui: "$font_ui";
\$saga-font-size: ${font_size}px;

\$saga-space-xs: ${space_xs}px;
\$saga-space-sm: ${space_sm}px;
\$saga-space-md: ${space_md}px;
\$saga-space-lg: ${space_lg}px;

\$saga-radius: ${radius}px;
\$saga-border-size: ${border_size}px;
\$saga-blur: ${blur}px;

\$saga-anim-windows: $anim_windows;
\$saga-anim-workspace: $anim_workspace;
SCSS

mkdir -p "$REPO_ROOT/desktop/waybar" "$REPO_ROOT/desktop/eww" "$REPO_ROOT/desktop/wofi" "$REPO_ROOT/desktop/hypr"

cat "$THEME_DIR/variables.css" "$THEME_DIR/waybar.css" > "$REPO_ROOT/desktop/waybar/style.css"
cat "$THEME_DIR/variables.scss" "$THEME_DIR/eww.scss" > "$REPO_ROOT/desktop/eww/eww.scss"
cat "$THEME_DIR/variables.css" "$THEME_DIR/launcher.css" > "$REPO_ROOT/desktop/wofi/style.css"

cat > "$REPO_ROOT/desktop/hypr/theme.conf" <<HYPR
# Generated by saga theme apply ($THEME_NAME)

general {
  border_size = $border_size
  col.active_border = rgb(${primary#\#}) rgb(${secondary#\#}) 45deg
  col.inactive_border = rgb(${accent#\#})
}

decoration {
  rounding = $radius

  blur {
    enabled = true
    size = 8
    passes = 3
    ignore_opacity = true
  }

  shadow {
    enabled = true
    render_power = 3
    color = rgba(157,78,221,0.35)
  }
}

animations {
  enabled = true
  animation = windows,1,$anim_windows,default
  animation = fade,1,$anim_windows,default
  animation = workspaces,1,$anim_workspace,default
}

misc {
  vfr = true
}
HYPR

mkdir -p "$HOME/.config/hrafn"
cat > "$HOME/.config/hrafn/theme.json" <<JSON
{
  "theme": "$THEME_NAME",
  "colors": {
    "agenda_time": "$hrafn_agenda_time",
    "agenda_title": "$hrafn_agenda_title",
    "task": "$hrafn_task",
    "empty": "$hrafn_empty",
    "meeting_starting_soon": "$hrafn_meeting_soon",
    "meeting_live": "$hrafn_meeting_live",
    "tasks_due_today": "$hrafn_tasks_due",
    "focus_window_available": "$hrafn_focus",
    "sync_status": "$hrafn_sync_status",
    "error": "$hrafn_error",
    "warning": "$hrafn_warning"
  },
  "fonts": {
    "ui": "$hrafn_font_ui",
    "display": "$hrafn_font_display",
    "size": $hrafn_font_size
  }
}
JSON

if [[ -d "$HOME/.local/share/saga" && -f "$HOME/.local/share/saga/state.json" ]] && command -v jq >/dev/null 2>&1; then
  tmp="$(mktemp)"
  jq --arg t "$THEME_NAME" '.active_theme = $t' "$HOME/.local/share/saga/state.json" > "$tmp"
  mv "$tmp" "$HOME/.local/share/saga/state.json"
fi

if command -v hyprctl >/dev/null 2>&1; then
  hyprctl reload >/dev/null 2>&1 || true
fi
if command -v pkill >/dev/null 2>&1; then
  pkill -SIGUSR2 waybar >/dev/null 2>&1 || true
fi
if [[ -x "$HOME/.local/share/saga/bin/eww" ]]; then
  "$HOME/.local/share/saga/bin/eww" --config "$HOME/.config/saga/widgets/eww" reload >/dev/null 2>&1 || true
fi
if command -v swaync-client >/dev/null 2>&1; then
  swaync-client -rs >/dev/null 2>&1 || true
fi

echo "applied theme: $THEME_NAME"
